language: go

go:
  - 1.2
  - 1.3
  - 1.4.3
  - tip

os:
  - linux
  - osx
  
before_install:
  - if [ ${TRAVIS_OS_NAME} == "linux" ]; then sudo apt-get update -q -y; fi
  - if [ ${TRAVIS_OS_NAME} == "linux" ]; then sudo apt-get install libnetcdf-dev -y; fi
  - if [ ${TRAVIS_OS_NAME} == "osx" ]; then brew tap homebrew/science; fi
  - if [ ${TRAVIS_OS_NAME} == "osx" ]; then brew update; fi
  - if [ ${TRAVIS_OS_NAME} == "osx" ]; then brew install netcdf; fi
  
script:
  - go install -v ./...
  - go test -v ./...