language: go

go:
  - 1.2
  - 1.3
  - 1.4.3
  - tip

os:
  - linux
  - osx
  
before_install:
  - if [ ${TRAVIS_OS_NAME} == "linux" ]; then sudo apt-get update -q -y; fi
  - if [ ${TRAVIS_OS_NAME} == "linux" ]; then sudo apt-get install libnetcdf-dev -y; fi
  - if [ ${TRAVIS_OS_NAME} == "osx" ]; then brew tap homebrew/science; fi
  - if [ ${TRAVIS_OS_NAME} == "osx" ]; then brew update; fi
  - if [ ${TRAVIS_OS_NAME} == "osx" ]; then brew install netcdf; fi
  - export PATH="$GOPATH/bin:$PATH"
  - go get github.com/fhs/go-netcdf/netcdf
  - go get github.com/pborman/getopt
  - go get github.com/BurntSushi/toml


install :
  - go install github.com/fhs/go-netcdf/netcdf
  - go install github.com/pborman/getopt
  - go install github.com/BurntSushi/toml
  - go install ../Oceano2oceansitesTest/toml
  - go install ../Oceano2oceansitesTest/roscop
  - go install ../Oceano2oceansitesTest/lib
  - go install ../Oceano2oceansitesTest/config
  - go install ../Oceano2oceansitesTest/analyse
  - go install ../Oceano2oceansitesTest/netcdf
  - go install ../Oceano2oceansitesTest/mk21
  - go install ../Oceano2oceansitesTest/seabird
  - go install ../Oceano2oceansitesTest/thecsas
  - go install ../Oceano2oceansitesTest/ifm
 
script:
  - go build -i
